// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: warmage/staking/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgVeDelegate struct {
	DelegatorAddress string     `protobuf:"bytes,1,opt,name=delegator_address,json=delegatorAddress,proto3" json:"delegator_address"`
	ValidatorAddress string     `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address"`
	VeId             string     `protobuf:"bytes,3,opt,name=ve_id,json=veId,proto3" json:"ve_id"`
	Amount           types.Coin `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount"`
}

func (m *MsgVeDelegate) Reset()         { *m = MsgVeDelegate{} }
func (m *MsgVeDelegate) String() string { return proto.CompactTextString(m) }
func (*MsgVeDelegate) ProtoMessage()    {}
func (*MsgVeDelegate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e184fbf70dc0649d, []int{0}
}
func (m *MsgVeDelegate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVeDelegate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVeDelegate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVeDelegate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVeDelegate.Merge(m, src)
}
func (m *MsgVeDelegate) XXX_Size() int {
	return m.Size()
}
func (m *MsgVeDelegate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVeDelegate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVeDelegate proto.InternalMessageInfo

type MsgVeDelegateResponse struct {
}

func (m *MsgVeDelegateResponse) Reset()         { *m = MsgVeDelegateResponse{} }
func (m *MsgVeDelegateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgVeDelegateResponse) ProtoMessage()    {}
func (*MsgVeDelegateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e184fbf70dc0649d, []int{1}
}
func (m *MsgVeDelegateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVeDelegateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVeDelegateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVeDelegateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVeDelegateResponse.Merge(m, src)
}
func (m *MsgVeDelegateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgVeDelegateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVeDelegateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVeDelegateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgVeDelegate)(nil), "warmage.staking.v1.MsgVeDelegate")
	proto.RegisterType((*MsgVeDelegateResponse)(nil), "warmage.staking.v1.MsgVeDelegateResponse")
}

func init() { proto.RegisterFile("warmage/staking/v1/tx.proto", fileDescriptor_e184fbf70dc0649d) }

var fileDescriptor_e184fbf70dc0649d = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x31, 0x8b, 0xd4, 0x40,
	0x14, 0xc7, 0x33, 0x77, 0xeb, 0xe1, 0x8d, 0x08, 0x67, 0xf0, 0x70, 0x5d, 0x65, 0x72, 0x06, 0x8b,
	0x53, 0xb8, 0x19, 0x72, 0x16, 0x82, 0x9d, 0x51, 0x10, 0x8b, 0x6b, 0x52, 0x58, 0xd8, 0x2c, 0x93,
	0xcd, 0x63, 0x1c, 0x4c, 0xe6, 0x85, 0xcc, 0x5c, 0x3c, 0x5b, 0x0b, 0xb1, 0x12, 0xc1, 0x2f, 0x70,
	0x1f, 0xe7, 0xca, 0x05, 0x1b, 0xab, 0x45, 0x76, 0x2d, 0x64, 0x3f, 0x82, 0x95, 0xec, 0x26, 0x1b,
	0x5d, 0x56, 0xb8, 0xee, 0xf1, 0xff, 0xbf, 0xf7, 0x1b, 0xfe, 0xef, 0x0d, 0xbd, 0xf3, 0x4e, 0x56,
	0x85, 0x54, 0x20, 0xac, 0x93, 0x6f, 0xb5, 0x51, 0xa2, 0x8e, 0x84, 0x3b, 0xe3, 0x65, 0x85, 0x0e,
	0x7d, 0xbf, 0x35, 0x79, 0x6b, 0xf2, 0x3a, 0x1a, 0xdc, 0x55, 0x88, 0x2a, 0x07, 0x21, 0x4b, 0x2d,
	0xa4, 0x31, 0xe8, 0xa4, 0xd3, 0x68, 0x6c, 0x33, 0x31, 0xb8, 0xa9, 0x50, 0xe1, 0xb2, 0x14, 0x8b,
	0xaa, 0x55, 0xd9, 0x08, 0x6d, 0x81, 0x56, 0xa4, 0xd2, 0x82, 0xa8, 0xa3, 0x14, 0x9c, 0x8c, 0xc4,
	0x08, 0xb5, 0x69, 0xfc, 0xf0, 0x37, 0xa1, 0xd7, 0x4f, 0xac, 0x7a, 0x05, 0xcf, 0x21, 0x07, 0x25,
	0x1d, 0xf8, 0x31, 0xbd, 0x91, 0x35, 0x35, 0x56, 0x43, 0x99, 0x65, 0x15, 0x58, 0xdb, 0x27, 0x07,
	0xe4, 0x70, 0x37, 0xde, 0x9f, 0x4f, 0x82, 0x4d, 0x33, 0xd9, 0xeb, 0xa4, 0xa7, 0x8d, 0xb2, 0x60,
	0xd4, 0x32, 0xd7, 0xd9, 0x1a, 0x63, 0xeb, 0x2f, 0x63, 0xc3, 0x4c, 0xf6, 0x3a, 0x69, 0xc5, 0x60,
	0xf4, 0x4a, 0x0d, 0x43, 0x9d, 0xf5, 0xb7, 0x97, 0x73, 0xbb, 0xf3, 0x49, 0xd0, 0x08, 0x49, 0xaf,
	0x86, 0x97, 0x99, 0xff, 0x98, 0xee, 0xc8, 0x02, 0x4f, 0x8d, 0xeb, 0xf7, 0x0e, 0xc8, 0xe1, 0xb5,
	0xe3, 0xdb, 0xbc, 0x89, 0xca, 0x17, 0x51, 0x79, 0x1b, 0x95, 0x3f, 0x43, 0x6d, 0xe2, 0xde, 0xc5,
	0x24, 0xf0, 0x92, 0xb6, 0xfd, 0xc9, 0xd5, 0x4f, 0xe7, 0x81, 0xf7, 0xeb, 0x3c, 0xf0, 0xc2, 0x5b,
	0x74, 0x7f, 0x2d, 0x7b, 0x02, 0xb6, 0x44, 0x63, 0xe1, 0xf8, 0x33, 0xa1, 0xdb, 0x27, 0x56, 0xf9,
	0x1f, 0x09, 0xa5, 0xff, 0xac, 0xe6, 0x1e, 0xdf, 0xbc, 0x0a, 0x5f, 0x23, 0x0c, 0x1e, 0x5c, 0xda,
	0xb2, 0x7a, 0x24, 0x7c, 0xf8, 0xe1, 0xdb, 0xcf, 0xaf, 0x5b, 0xf7, 0xfd, 0x50, 0xfc, 0xf7, 0x23,
	0x88, 0x1a, 0x86, 0xed, 0x62, 0x21, 0x7e, 0x71, 0x31, 0x65, 0x64, 0x3c, 0x65, 0xe4, 0xc7, 0x94,
	0x91, 0x2f, 0x33, 0xe6, 0x8d, 0x67, 0xcc, 0xfb, 0x3e, 0x63, 0xde, 0xeb, 0x23, 0xa5, 0xdd, 0x9b,
	0xd3, 0x94, 0x8f, 0xb0, 0x10, 0x25, 0xb8, 0x4a, 0x1f, 0xe5, 0x32, 0xb5, 0x1d, 0xf2, 0xac, 0x83,
	0xba, 0xf7, 0x25, 0xd8, 0x74, 0x67, 0x79, 0xf6, 0x47, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x51,
	0xa4, 0x1c, 0xca, 0x7d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// VeDelegate defines a method for performing a delegation of ve-locked coins
	// from a delegator to a validator.
	VeDelegate(ctx context.Context, in *MsgVeDelegate, opts ...grpc.CallOption) (*MsgVeDelegateResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) VeDelegate(ctx context.Context, in *MsgVeDelegate, opts ...grpc.CallOption) (*MsgVeDelegateResponse, error) {
	out := new(MsgVeDelegateResponse)
	err := c.cc.Invoke(ctx, "/warmage.staking.v1.Msg/VeDelegate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// VeDelegate defines a method for performing a delegation of ve-locked coins
	// from a delegator to a validator.
	VeDelegate(context.Context, *MsgVeDelegate) (*MsgVeDelegateResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) VeDelegate(ctx context.Context, req *MsgVeDelegate) (*MsgVeDelegateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VeDelegate not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_VeDelegate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVeDelegate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VeDelegate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/warmage.staking.v1.Msg/VeDelegate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VeDelegate(ctx, req.(*MsgVeDelegate))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "warmage.staking.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VeDelegate",
			Handler:    _Msg_VeDelegate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "warmage/staking/v1/tx.proto",
}

func (m *MsgVeDelegate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVeDelegate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVeDelegate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.VeId) > 0 {
		i -= len(m.VeId)
		copy(dAtA[i:], m.VeId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.VeId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DelegatorAddress) > 0 {
		i -= len(m.DelegatorAddress)
		copy(dAtA[i:], m.DelegatorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DelegatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgVeDelegateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVeDelegateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVeDelegateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgVeDelegate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DelegatorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.VeId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgVeDelegateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgVeDelegate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVeDelegate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVeDelegate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVeDelegateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVeDelegateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVeDelegateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
